apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-health
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s
    repoURL: 'https://github.com/alejandro945/my-health-ops/'
    targetRevision: dev
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - Replace=true