kubectl apply -f namespaces/
kubectl apply -f configMaps/
kubectl apply -f clusterRoles/
kubectl apply -f volumes/
kubectl apply -f secrets/
kubectl apply -f pods/
kubectl apply -f hpa/
kubectl apply -f services/
kubectl apply -f ingress/