apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: alejandro945/my-health-dev_client:2
        ports:
        - containerPort: 8083
        env:
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: client-sc
              key: PORT
        - name: SERVER_URL
          valueFrom:
            secretKeyRef:
              name: client-sc
              key: SERVER_URL