apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: myhealthcontainerregistry.azurecr.io/my-health-server:1.0.0-6
        ports:
        - containerPort: 9000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: server-sc
              key: DATABASE_URL
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: server-sc
              key: PORT
