apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: runners
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  type: LoadBalancer
  loadBalancerIP: 20.253.97.127
  selector:
    app: jenkins-server
  ports:
    - port: 8080
      targetPort: 8080
      # nodePort: 32000