apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
  - alert-manager-svc.yaml
  - client-svc.yaml
  - grafana-service.yaml
  - jenkins-svc.yaml
  - prometheus-svc.yaml
  - server-svc.yaml
  - sonarqube-svc.yaml